# Generated by Django 3.2.5 on 2021-07-31 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
                ('category_slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('rank', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_sub_slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('sub_name', models.CharField(max_length=20)),
                ('rank', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='news_app.postcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('intro_link', models.URLField(blank=True, null=True)),
                ('post_slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('intro', models.CharField(max_length=200)),
                ('summary_one', models.TextField(blank=True, null=True)),
                ('summary_two', models.TextField(blank=True, null=True)),
                ('summary_three', models.TextField(blank=True, null=True)),
                ('summary_four', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('scategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='news_app.postsubcategory')),
            ],
        ),
    ]
