# Generated by Django 3.2.5 on 2021-07-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='postsubcategory',
            old_name='post_sub_slug',
            new_name='slug',
        ),
    ]
