# Generated by Django 3.2.5 on 2021-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20210804_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubcategory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
