# Generated by Django 3.2.5 on 2021-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_auto_20210811_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='primary_featured',
            field=models.BooleanField(default=False),
        ),
    ]
