# Generated by Django 3.2.5 on 2021-08-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0011_alter_post_primary_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
