# Generated by Django 3.2.5 on 2021-08-12 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_app', '0012_alter_post_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auhor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='auth.user'),
            preserve_default=False,
        ),
    ]
