# Generated by Django 3.2.5 on 2021-08-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_post_auhor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhor',
            new_name='author',
        ),
    ]
