# Generated by Django 3.2.5 on 2021-08-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0016_alter_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
