# Generated by Django 3.2.5 on 2021-08-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0020_comment_comment_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bangla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='bangla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postsubcategory',
            name='bangla',
            field=models.BooleanField(default=False),
        ),
    ]
