# Generated by Django 3.2.5 on 2021-08-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0021_auto_20210821_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, null=True, unique=True),
        ),
    ]
